version: '3'

services:
    db:
        build:
          context: ./etc/postgresql
          dockerfile: Dockerfile
        container_name: postgresql
        volumes:
            - "./var/postgresql/data:/bitnami/postgresql/data"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: magical_password_for_root
            POSTGRES_DB: zabbix_server_db
            DB_PORT: 5432
            
#    pgadmin: 
#        image: dpage/pgadmin4
#        environment:
#            PGADMIN_DEFAULT_EMAIL: xxx@xxx.com
#            PGADMIN_DEFAULT_PASSWORD: magical_password_for_root
#            PGADMIN_LISTEN_PORT: 80
#        ports:
#            - 8083:80
#        links: 
#            - db
           
    zabbix-server:
        container_name: zabbix-server
        build: 
          context: ./etc/zabbix
        links:
            - db
        ports:
            - 10051:10051
        environment:
            POSTGRES_USER: root
            POSTGRES_DB : zabbix_server_db
            POSTGRES_PASSWORD: magical_password_for_root
            DB_SERVER_HOST: db
            DB_PORT: 5432
            
    zabbix-web:
        container_name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql
        ports:
            - 8080:8080
        links:
            - db
         # To fix permission, run:
         # docker exec -it -u root zabbix-web chmod 755 /etc/nginx/ssl
         # docker exec -it -u root zabbix-web chmod 755 /etc/nginx/options-ssl-nginx.conf
         # docker exec -it -u root zabbix-web chmod 755 /etc/ssl/certs/dhparam-2048.pem
         #
         # docker exec -it -u root zabbix-web chown -R zabbix:root /etc/nginx/ssl
         # docker exec -it -u root zabbix-web chmod zabbix:root /etc/nginx/options-ssl-nginx.conf
         # docker exec -it -u root zabbix-web chmod zabbix:root /etc/ssl/certs/dhparam-2048.pemu
         # docker-compose restart zabbix-web
        volumes:
            - ./etc/zabbix-web/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - ./etc/zabbix-web/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
            - ./etc/zabbix-web/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - ./etc/certbot/letsencrypt:/etc/nginx/ssl
        environment:
            ZBX_SERVER_HOST: zabbix-server
            DB_SERVER_HOST : db
            DB_SERVER_PORT : 5432
            POSTGRES_USER : root
            POSTGRES_PASSWORD: magical_password_for_root
            POSTGRES_DB: zabbix_server_db
            
    nodejs-cronjob:
        build:
          context: ./etc/nodejs
          dockerfile: Dockerfile
        links:
            - zabbix-server
        environment:
            ZABBIX_SERVER: zabbix-server
            ZABBIX_HOSTNAME: dev.Simulator.LambdaFunction
        volumes:
            - "./app/cronjob:/usr/src/app"            

    fluentd:
        build: 
          context: ./etc/fluentd
          dockerfile: Dockerfile
        environment:
            ZABBIX_SERVER: zabbix-server
            ZABBIX_HOSTNAME: nodejs-cronjob
        volumes:
          - "./etc/fluentd/conf:/fluentd/etc"
          - "./var/fluentd/log/:/var/log/"
        ports:
          - "24224:24224"
          - "24224:24224/udp"